version: '3.8'

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/db.sqlite3:/app/db.sqlite3

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    # volumes:
    #   - ./frontend:/app
    # depends_on:
    #   - backend

  # database:
  #   image: postgres:latest
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: example
  #     POSTGRES_DB: mydatabase
