# Generated by Django 5.0.4 on 2024-04-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_earning_month_transaction_delete_earnings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='name',
        ),
        migrations.AddField(
            model_name='month',
            name='month',
            field=models.IntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], default=1, unique=True),
            preserve_default=False,
        ),
    ]
